bug1-2修正しました
hoangthinh2802/ex-emp-management-bugfix pull request #2
Opened 2022-06-09 05:30 UTC by hoangthinh2802

入力値チェック機能を修正しました。
確認お願いします

2022-06-09 05:44 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-06-09 05:44 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/form/LoginForm.java
> +	@Size(min = 1, message = "値を入力してください")
今回の要望は【管理者を登録する】のユースケースのみです。
ログイン時は入力値チェックをする必要はないため、戻してください。

2022-06-09 05:44 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/controller/AdministratorController.java
> +	public String toInsert(Model model, InsertAdministratorForm form) {
Model model, InsertAdministratorForm form

上記２つの引数を増やしていますが？必要ですか？
必要なければ削除をお願いします。

2022-06-09 05:49 UTC, hoangthinh2802 commented on src/main/java/jp/co/sample/emp_management/form/LoginForm.java
> +	@Size(min = 1, message = "値を入力してください")
承知しました。やり直します。

2022-06-09 21:52 UTC, igamasayuki requested changes
今回の要望は【管理者を登録する】のユースケースのみです。
ログイン時は入力値チェックをする必要はないため、戻してください。

もし不明点があれば口頭でご相談くださいね。

2022-06-09 21:52 UTC, igamasayuki commented on src/main/java/jp/co/sample/emp_management/form/LoginForm.java
> +	@Size(min = 1, message = "値を入力してください")
こちら修正されていますか？

2022-06-10 00:13 UTC, igamasayuki approved these changes
とてもわかりやすくなったと思います。
承認します。

2022-06-10 00:13 UTC, merged